<a href="https://colab.research.google.com/github/Gargi2305/Business-Analytics-Using-Python/blob/main/assignment%201/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

mat=np.arange(16).reshape(4,4)
mat=mat.transpose()
print(mat)
mat=mat.reshape(2,8)
print(mat)

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12  1  5  9 13]
 [ 2  6 10 14  3  7 11 15]]
